on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ankurv3rma/ts-action-test@main
        with:
          namespace: "testing-tenant"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
